name: tripsociety
favicon: null
layout_spectrum: 0.45549426740035415
typography_spectrum: 0.5224341787397861
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ee008c'
    - '#6dcff6'
    - '#f68122'
    - '#241e20'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
